apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tool-cert
  namespace: web-stock-future
spec:
  secretName: tool-tls
  dnsNames:
    - tool.nefyo.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  privateKey:
    algorithm: RSA
    size: 2048
  solvers:
    - http01:
        ingress:
          class: traefik