---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: tool-whitelist-30050
  namespace: web-stock-future
spec:
  ipWhiteList:
    sourceRange:
      - "127.0.0.1/32"      # Local access
      - "10.42.0.0/16"      # K3s internal pod network
      - "192.168.0.0/16"    # Internal LAN network
      - "172.16.0.0/12"     # Docker internal network
      # Thêm IP được phép truy cập vào đây:
      - "1.2.3.4/32"        # Thay bằng IP công ty/nhà của bạn
      - "5.6.7.8/32"        # Thêm IP khác nếu cần
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tool-service-ingress
  namespace: web-stock-future
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: web-stock-future-tool-whitelist-30050@kubernetescrd
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - tool.nefyo.com
      secretName: tool-tls
  rules:
    - host: tool.nefyo.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tool-service
                port:
                  number: 9999