---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config-30050
  namespace: kube-system
data:
  traefik.yml: |
    entryPoints:
      web-secure-30050:
        address: ":30050"
    
    api:
      dashboard: true
      
    providers:
      kubernetesIngress: {}
      kubernetesCRD: {}
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-30050
  namespace: kube-system
spec:
  type: NodePort
  ports:
    - name: web-30050
      port: 30050
      targetPort: 30050
      nodePort: 30050
      protocol: TCP
  selector:
    app.kubernetes.io/name: traefik