apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: elasticsearch
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: promtail-sa # QUAN TRỌNG: Dùng tài khoản có quyền list pods
      containers:
        - name: promtail
          image: grafana/promtail:2.9.4
          args:
            - "-config.file=/etc/promtail/config.yml"
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: logs
              mountPath: /var/log/pods # K3s lưu log ở đây
              readOnly: true
            - name: config
              mountPath: /etc/promtail
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
      volumes:
        - name: logs
          hostPath:
            path: /var/log/pods
        - name: config
          configMap:
            name: promtail-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: elasticsearch
data:
  config.yml: |
    server:
      http_listen_port: 9080
    clients:
      - url: http://loki-service:3100/loki/api/v1/push
    scrape_configs:
    - job_name: kubernetes-pods
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        target_label: app
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod