apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-stock-future-ingress
  namespace: web-stock-future
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  traefik.ingress.kubernetes.io/router.middlewares: "web-stock-future/web-stock-future-no-cache@kubernetescrd"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - api.iprime.primecapitalvn.com
        - iprime.primecapitalvn.com
      secretName: web-stock-future-cert-secret
  rules:
    - host: api.iprime.primecapitalvn.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-stock-future-backend-service
                port:
                  number: 7000
    - host: iprime.primecapitalvn.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-stock-future-frontend-service
                port:
                  number: 7001
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: web-stock-future-no-cache
  namespace: web-stock-future
spec:
  headers:
    customResponseHeaders:
      Cache-Control: "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
