apiVersion: networking.k8s.io/v1
kind: Ingress
spec:
metadata:
  name: web-game-ingress
  namespace: web-game
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - api2.gamehearth.com
      secretName: web-game-cert-secret
  rules:
    - host: api2.gamehearth.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 5000
