apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-job
  namespace: backup
spec:
  schedule: "0 2 */2 * *" # Chạy lúc 2h sáng mỗi 2 ngày
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup
              image: postgres:15-alpine
              command:
                - /bin/sh
                - -c
                - |
                  mkdir -p /backup
                  BACKUP_FILE="/backup/all_db_$(date +%F).tar"
                  if pg_dumpall -h "$PG_HOST" -U "$PG_USER" | tar -cvf "$BACKUP_FILE" - ; then
                    find /backup -type f -mtime +3 -delete
                  else
                    echo "Backup failed, old backups not deleted."
                  fi
              env:
                - name: PG_HOST
                  value: "postgres-service"
                - name: PG_USER
                  value: "postgres"
                - name: PGPASSWORD
                  value: "Anhyeuem123@"
                # Không cần khai báo PG_DB và ES_HOST nữa
              volumeMounts:
                - name: backup-volume
                  mountPath: /backup
          restartPolicy: OnFailure
          volumes:
            - name: backup-volume
              persistentVolumeClaim:
                claimName: backup-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc
  namespace: backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
