apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: postgresql
data:
  init-multi-db.sh: |
    #!/bin/bash
    set -e
    if [ -n "$POSTGRES_MULTIPLE_DATABASES" ]; then
      echo "Multiple database creation requested: $POSTGRES_MULTIPLE_DATABASES"
      for db in $(echo $POSTGRES_MULTIPLE_DATABASES | tr ',' ' '); do
        echo "Creating database: $db"
        psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
          CREATE DATABASE "$db";
EOSQL
      done
    fi
