apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
            requests:
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: elasticsearch
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000 # Cổng này bạn sẽ dùng để truy cập: http://IP-CUA-BAN:32000
  type: NodePort # Hoặc dùng Ingress để truy cập từ ngoài